name: phy
channels:
  - kwikteam
dependencies:
  - python
  - pip
  - numpy=1.9
  - vispy
  - matplotlib
  - scipy
  - h5py
  - pyqt
  - ipython
  - requests
  - traitlets
  - six
  - ipyparallel
  - joblib
  - cython
  - click
  - cloudpickle
  - toolz
  - pip:
    - klustakwik2
    - git+https://github.com/kwikteam/phy.git@kill-kwik
