name: phy
channels:
  - kwikteam
dependencies:
  - python
  - pip
  - numpy=1.9
  - vispy
  - matplotlib
  - scipy
  - h5py
  - pyqt
  - requests
  - traitlets
  - six
  - joblib
  - click
  - pip:
    - klusta
    - klustakwik2
    - git+https://github.com/kwikteam/phy.git@kill-kwik
